### ISSUE TITLE
[1.20.1 Server] Crash on startup with Improved Mobs mod

### ISSUE THREAD

**Issue by MrKashew** [CERBON-MODS/Queen-Bee#2]
Modloader
Forge

Minecraft version
1.20.1

Modloader version
47.1.43

https://gist.github.com/MrKashew/529f2ba395f9d3c7d784a4c5154b9146
tried with latest mod version afterwards and same crash still

**Comment by MrKashew** [comment]
note: removing this mod while keeping Improved Mobs did solve crash

**Comment by CerbonXD** [comment]
Seems to be an issue with my armor materials class. That's strange, though; nothing seems to be wrong. I will take a closer look into it and bring a fix as soon as possible. Thanks for letting me know about this issue.

**Comment by CerbonXD** [comment]
Well, actually, the issue seems to be from Forge. The Improved Mobs mod needs at least version 47.1.3. When downgrading the Forge version from 47.1.43 to 47.1.3, I had no issues. Please downgrade your Forge version if possible, and in case it does not work for you, please let me know.

**Comment by drakray** [comment]
Hi there, I got a crash with Minecolonies, very similar to this one, https://github.com/ldtteam/minecolonies/issues/9599
referencing this line also ```at com.cerbon.queen_bee.item.QBArmorMaterials.m_7366_(QBArmorMaterials.java:54)```
Using Neoforge 47.1.79, and downgrading is no longer an option

**Comment by Sandriell** [comment]
@CerbonXD 

Similar issue. Downgrading Forge is not an option due to other mod's minimum version requirements.

https://gist.github.com/Sandriell/106b5083497a1cd396bf4e7036d7f620
